### PR TITLE
Remove unnecessary validations from user along with corresponding tests

### PR DESCRIPTION
**Pull request by annadolan**
@meganft @jmejia 
Working on changing the sign up form according to Rachel's new preferences. She is asking for a two-page account creation process, which starts with a form for name, email, and password, then creates an account and moves on to a second form requesting address, phone number, and profile picture.

### CODE REVIEW

**Comment by jmejia** [comment]
@annadolan Not sure what your plan is but multistep forms can be surprisingly tricky. Here's a post that explains how to approach them: http://blog.honeybadger.io/multi-step-forms-in-rails/

**Comment by jmejia** [comment]
@annadolan If you're already going down a different path, that is fine too. Just take a look at the article to see that perspective.

**Comment by annadolan** [comment]
@jmejia Rachel was ok with having the attributes on the second form be optional, thankfully. I had to make a custom route but I'm through that part. I'm having some issue getting our google maps gem to work, but one thing at a time, I guess. Thanks!

**Comment by jmejia** [comment]
@annadolan That's good 😅 

Tag me if you want me to take a look at the Gmaps stuff.

**Comment by annadolan** [comment]
@meganft Ready to merge! 💯

**Comment by meganft** [comment]
🏅 
Awesome @annadolan

**Pull request merged**
