### PR TITLE
Style update form

### PR DESCRIPTION
**Pull request by annadolan**
@meganft 
I added styling to the update form, but I also changed it so it doesn't require a password. I commented out the test for requiring the password on update, and everything else is passing. I just want to get your opinion on this before merging - maybe we could have password reset on another page, or use Twilio for password reset? ❓

### CODE REVIEW

**Comment by meganft** [comment]
@annadolan 
I am totally fine with that. It seems like another unnecesaary step that could get in people's ways. I say we take out the need for password there!

**Comment by annadolan** [comment]
@meganft Perfect, thanks!

**Comment by annadolan** [comment]
@meganft ready to merge!

**Comment by meganft** [comment]
👌🔥

**Pull request merged**
